In [6]:
import requests
import pandas as pd

In [3]:
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp.raise_for_status()
resp

In [5]:
data = resp.json()
data[0]['title']

'ENH: frozensets are shown in parentheses (like tuples)'

In [7]:
issues = pd.DataFrame(data, columns=['numbers', 'title', 'labels', 'states'])
issues

,numbers,title,labels,states
0,NaN,ENH: frozensets are shown in parentheses (like...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",NaN
1,NaN,BUG: ValueError in pandas.DataFrame.replace wi...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",NaN
2,NaN,Remove editable installs from CI,[],NaN
3,NaN,ENH: Better error message for trying to conver...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",NaN
4,NaN,BUG: Pandas to_sql 'Engine' object has no attr...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",NaN
5,NaN,Relax meson pins in CI,"[{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...",NaN
6,NaN,BUG: boolean series .isin([pd.NA])] inconsiste...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",NaN
7,NaN,BUG: scalar out of bounds input does not raise...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",NaN
8,NaN,ENH: Change default dtype of `str.get_dummies(...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",NaN
9,NaN,ENH: Support attrs in feather files,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",NaN
10,NaN,BUG: DataFrame.sort_values() by 2 columns and ...,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",NaN
11,NaN,BUG: .to_period with MonthBegin offset does no...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",NaN
12,NaN,ENH: Add support for executing UDF's using Bod...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",NaN
13,NaN,Implement String Accumulations with nanoarrow,[],NaN
14,NaN,Update docs for generating unoptimized debug b...,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",NaN
15,NaN,BUG: Pandas resets counter when using filterwa...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",NaN
16,NaN,ENH: Enable pytables to round-trip with String...,"[{'id': 47229190, 'node_id': 'MDU6TGFiZWw0NzIy...",NaN
17,NaN,String dtype: disallow specifying the 'str' dt...,"[{'id': 57522093, 'node_id': 'MDU6TGFiZWw1NzUy...",NaN
18,NaN,ENH: Remove `mode` property from `BaseBuffer`,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",NaN
19,NaN,TST(string dtype): Resolve replace xfails,"[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...",NaN
20,NaN,Added improvements to the cheat sheet based on...,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",NaN
21,NaN,ENH: Add `date_format` and `date_unit` to `to_...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",NaN
22,NaN,DEPS: Bump optional dependencies,"[{'id': 527603109, 'node_id': 'MDU6TGFiZWw1Mjc...",NaN
23,NaN,Replace flake8-rst with flake8-rst-docstrings,[],NaN
24,NaN,TST (string dtype): clean-up interpolate tests,"[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...",NaN
25,NaN,QST:,"[{'id': 34444536, 'node_id': 'MDU6TGFiZWwzNDQ0...",NaN
26,NaN,BUG: CustomBusinessDay not respecting calendar,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",NaN
27,NaN,BUG: max on `axis=1` returns wrong values on t...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",NaN
28,NaN,BUG: MultiIndex union/difference not commutative,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",NaN
29,NaN,ENH: Change default dtype of str.get_dummies()...,[],NaN